server:
  port: 9014
  shutdown: graceful
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr-application
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hr
          jwk-set-uri: http://localhost:8080/realms/hr/protocol/openid-connect/certs


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/createTables/changeLog.yaml

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: info
    org.springframework.boot.devtools: debug
