version: "3.8"

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:15.5.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ${HOME}/work/volume/psql:/bitnami/postgresql
      - ${HOME}/work/docker-compose/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - hr-network
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
    networks:
      - hr-network
    depends_on:
      postgresql:
        condition: service_started
networks:
  hr-network:
    name: hr-network
